build:
  maxIssues: 0
  excludeCorrectable: false
  weights:
    # complexity: 2
    # LongParameterList: 1
    # style: 1
    # comments: 1

config:
  validation: true
  warningsAsErrors: false
  checkExhaustiveness: false
  # when writing own rules with transitive dependencies, report them
  # checkConfiguration: false
  # exclude:
  #   - 'build.gradle'
  #   - '.*/test/.*'

# For more information about rules visit https://detekt.dev/rules.html
complexity:
  active: true
  ComplexCondition:
    active: true
    threshold: 4
  ComplexInterface:
    active: true
    threshold: 10
  ComplexMethod:
    active: true
    threshold: 15
  CyclomaticComplexity:
    active: true
    threshold: 15
  LargeClass:
    active: true
    threshold: 600
  LongMethod:
    active: true
    threshold: 60
  LongParameterList:
    active: true
    threshold: 6
  MethodOverloading:
    active: true
    threshold: 6
  StringLiteralDuplication:
    active: true
    threshold: 3
    excludes: ['**/test/**', '**/androidTest/**', '**/commonTest/**', '**/jvmTest/**']
    excludeStrings: '""'
    ignoreAnnotation: false
    ignoreStringsAlphabeticalOrder: true
  TooManyFunctions:
    active: true
    thresholdInFiles: 11
    thresholdInClasses: 11
    thresholdInInterfaces: 11
    thresholdInObjects: 11
    thresholdInEnums: 11

naming:
  active: true
  ClassNaming:
    active: true
    classPattern: '[A-Z$][a-zA-Z0-9$]*'
  FunctionNaming:
    active: true
    functionPattern: '[a-z][a-zA-Z0-9]*'
    excludeClassPattern: '$^'
  PackageNaming:
    active: true
    packagePattern: '[a-z]+(\.[a-z][A-Za-z0-9]*)*'
  VariableNaming:
    active: true
    variablePattern: '[a-z][a-zA-Z0-9]*'
    excludeClassPattern: '$^'

style:
  active: true
  MaxLineLength:
    active: true
    maxLineLength: 120
  MagicNumber:
    active: true
    excludes: ['**/test/**', '**/androidTest/**', '**/commonTest/**', '**/jvmTest/**', '**/build.gradle.kts', '**/build.gradle', '**/settings.gradle.kts', '**/settings.gradle']
    ignoreNumbers: ['-1', '0', '1', '2']
    ignoreHashCodeFunction: true
    ignorePropertyDeclaration: false
    ignoreLocalVariableDeclaration: false
    ignoreConstantDeclaration: true
    ignoreCompanionObjectPropertyDeclaration: true
    ignoreAnnotation: false
    ignoreNamedArgument: true
    ignoreEnums: false
    ignoreRanges: false
